### ISSUE TITLE
Error when building under win7

### ISSUE THREAD

**Issue by honglei** [fancycode/python-libevent#1]
F:\Python\LibEvent\fancycode-python-libevent-cd2c5c7>python setup.py build
running build
running build_py
running build_ext
building '_libevent' extension
F:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W
3 /GS- /DNDEBUG -I.\libevent-2.0.13-stable\include -IC:\Python27\include -IC:\Py
thon27\PC /Tcsrc/_libevent.c /Fobuild\temp.win32-2.7\Release\src/_libevent.obj
_libevent.c
src/_libevent.c(59) : error C2198: 'evutil_socket_geterror' : too few arguments
for call
error: command '"F:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe"' fa
iled with exit status 2

**Comment by fancycode** [comment]
Fixed in 888bd7f, thanks for reporting.

**Comment by honglei** [comment]
I still met the following error:

1) in pybase.c  the macro 'suseconds_t' is not defined, its long in win32 platform

2) VC2008 compiler specefic errors in pyhttp.c

658d657
<       struct evbuffer *buffer = NULL;
661,662c660,662
<         }      

## <         buffer = evbuffer_new();

> ```
>     }
> 
>     struct evbuffer *buffer = evbuffer_new();
> ```
> 
> 721d720
> <       struct evbuffer *buffer = NULL;
> 726c725
> 
> ## <         buffer = evbuffer_new();
> 
> ```
>     struct evbuffer *buffer = evbuffer_new();
> ```

3) setup.py for link errors.

59c59,61

## < extra_link_args = [ ]

> extra_link_args = [
>     os.path.join(LIBEVENT_ROOT, '.libs', 'libevent.a'),
> ]
> 63d64
> <         os.path.join(LIBEVENT_ROOT, '.libs', 'libevent.a'),
> 68,75d68
> < elif os.name == 'nt':
> <     # enable thread support
> <     extra_link_args.extend([
> <         os.path.join(LIBEVENT_ROOT,  'libevent.lib'),
> <     ])  
> <     libraries.append('ws2_32')
> <     libraries.append('Advapi32')
> <  
> 79,80c72
> <         extra_link_args=extra_link_args,#define_macros=[('_WIN32_WINNT', '0x0600')]
> 
> ## <         ),
> 
> ```
>     extra_link_args=extra_link_args),
> ```

after fixed these problem. i have build and installed it!

**Comment by fancycode** [comment]
Could you please provide a unified diff by executing "git diff" in your checkout?

**Comment by honglei** [comment]
I pasted in the attached file.

**Comment by honglei** [comment]
``` diff
Author: unknown <hongleij@.(none)>  2011-08-31 09:04:36
Committer: unknown <hongleij@.(none)>  2011-08-31 09:04:36
Parent: 888bd7feaf73606dd4737c617db23ad45024a059 (added missing parameter when calling "evutil_socket_geterror" (GitHub #1))
Branch: master
Follows: v0.9.1
Precedes: 

    build and install under VC2008/Win7

----------------------------------- setup.py -----------------------------------
index 8c5ee69..b8b25e9 100644
@@ -56,16 +56,23 @@ library_dirs = [
 ]
 libraries = [
 ]
-extra_link_args = [
-    os.path.join(LIBEVENT_ROOT, '.libs', 'libevent.a'),
-]
+extra_link_args = [ ]
 if os.name == 'posix':
     # enable thread support
     extra_link_args.extend([
+        os.path.join(LIBEVENT_ROOT, '.libs', 'libevent.a'),
         os.path.join(LIBEVENT_ROOT, '.libs', 'libevent_pthreads.a'),
     ])
     libraries.append('rt')
     libraries.append('pthread')
+elif os.name == 'nt':
+    # enable thread support
+    extra_link_args.extend([
+        os.path.join(LIBEVENT_ROOT,  'libevent.lib'),
+    ])    
+    libraries.append('ws2_32')
+    libraries.append('Advapi32')
+    
 extens = [
     Extension('_libevent', c_files, libraries=libraries,
         include_dirs=include_dirs, library_dirs=library_dirs,

--------------------------------- src/pybase.c ---------------------------------
index 02a2eee..bf80724 100644
@@ -26,6 +26,10 @@

 #include "pybase.h"

+#ifdef WIN32
+  #define suseconds_t long
+#endif
+
 typedef struct _PyConfigObject {
     PyObject_HEAD
     struct event_config *config;

--------------------------------- src/pyhttp.c ---------------------------------
index 4b22e1e..90714e7 100644
@@ -655,11 +655,11 @@ pyhttp_request_send_reply(PyHttpRequestObject *self, PyObject *args)
         evhttp_send_reply(self->request, code, reason, ((PyBufferObject *) data)->buffer);
         Py_END_ALLOW_THREADS
     } else {
+       struct evbuffer *buffer = NULL;
         if (PyObject_AsReadBuffer(pydata, (const void **) &data, &length) != 0) {
             return NULL;
-        }
-        
-        struct evbuffer *buffer = evbuffer_new();
+        }      
+        buffer = evbuffer_new();
         if (buffer == NULL) {
             return PyErr_NoMemory();
         }
@@ -718,11 +718,12 @@ pyhttp_request_send_reply_chunk(PyHttpRequestObject *self, PyObject *args)
         evhttp_send_reply_chunk(self->request, ((PyBufferObject *) data)->buffer);
         Py_END_ALLOW_THREADS
     } else {
+       struct evbuffer *buffer = NULL;
         if (PyObject_AsReadBuffer(pydata, (const void **) &data, &length) != 0) {
             return NULL;
         }

-        struct evbuffer *buffer = evbuffer_new();
+        buffer = evbuffer_new();
         if (buffer == NULL) {
             return PyErr_NoMemory();
         }
```

**Comment by fancycode** [comment]
Committed in eb0824f, thanks.
